# 6-8. Тест: Векторные пространства и NumPy

In [8]:
import numpy as np
from numpy.linalg import norm

In [143]:
# Задание Выберите те наборы векторов, которые являются линейно независимыми 
# (1, 0), (0, 1)
# (1, 0), (0, 1), (-1, 1)
# (1, 0) - один из векторов нулевой?
# (1, 0), (1, 1)
v1 = np.array([[1, 0], [0, 1]])
v2 = np.array([[1, 0], [0, 1], [1, 1]])
v3 = np.array([1, 0])
v4 = np.array([[1, 0], [1, 1]])
print np.linalg.matrix_rank(v1), v1.shape, v1.ndim # Независим
print np.linalg.matrix_rank(v2), v2.shape, v2.ndim # Зависим
print np.linalg.matrix_rank(v3), v3.shape, v3.ndim # Зависим
print np.linalg.matrix_rank(v4), v4.shape, v4.ndim # Независим

2 (2L, 2L) 2
2 (3L, 2L) 2
1 (2L,) 1
2 (2L, 2L) 2


In [144]:
# Примеры разобраться 

print np.eye(4)
print np.linalg.matrix_rank(np.eye(4)), np.ndim(np.eye(4))
I=np.eye(4)
I[-1,-1] = 0.
print I
print np.linalg.matrix_rank(I), np.ndim(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
4 2
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
3 2


In [145]:
# Задание. Чему равна манхэттенская норма вектора а = (-1, 2, -1)?
am =  np.array([-1, 2, -1])
np.linalg.norm(a) # Евклидова норма

12.84523257866513

In [146]:
print a
def manhNorm (normVect): # Реализуем функцию Манхетенской нормы
    norm = 0;
    for x in normVect:
        norm += abs(x)
    return norm

manhNorm(am)

[ 8 10 -1  0  0]


4

In [147]:
# Альтеранатива
sum([abs(n) for n in am])

4

In [149]:
## Задание. Чему равно скалярное произведение векторов а = (1, 2, 3) и b = (-3, 1, 1)?
a = np.array([1, 2, 3])
b = np.array([-3, 1, 1])

def scalarMultiply(c, v): # Реализуем функцию скалярного умножения - это другое - это объединение векторов в один с перемножением всех элементов
    return np.array([c * vi for vi in v])

scalarMultiply(a, b)

array([[-3, -6, -9],
       [ 1,  2,  3],
       [ 1,  2,  3]])

In [150]:
# Умножение элементов друг на друга
a * b

array([-3,  2,  3])

In [151]:
?zip

In [152]:
# Скалярное произведение = сумма произведений элементов векторов
sum(ai * bi for ai, bi in zip(a, b))

2

In [153]:
np.dot(a, b)

2

In [82]:
## Задание В пространствах какой размерности можно выбрать k линейно независимых векторов? k, k-1, k+1
y1 = np.array([1,0,3])
print y1
print np.linalg.matrix_rank(y1), y1.ndim

1 1
[1 0 3]


In [154]:
# Задание Какие из нижеприведенных команд корректно отработают и создадут вектор? 
b = np.array(1, 2, 3, 4, 5, dtype=float)
b

ValueError: only 2 non-keyword arguments accepted

In [155]:
c = np.array([False, False, True])
c

array([False, False,  True])

In [156]:
d = np.array([1, 2, 3, 4, 5], dtype=float)
d

array([1., 2., 3., 4., 5.])

In [157]:
f = np.arange(1, 2, 0.3, dtype=float)
f

array([1. , 1.3, 1.6, 1.9])

In [124]:
## Задание Пусть даны два вектора a = np.array([6, 3, -5]) и b = np.array([-1, 0, 7]). 
#Какая из следующих команд считает евклидово расстояние между этими векторами?
import scipy.spatial
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])
# https://docs.scipy.org/doc/scipy/reference/spatial.distance.html

# Евклидово расстояние

In [125]:
scipy.spatial.distance.cdist(b, a, metric='euclidean') 

ValueError: XA must be a 2-dimensional array.

In [126]:
scipy.spatial.distance.cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')

array([[14.2126704]])

In [127]:
np.linalg.norm(a, ord=2) - np.linalg.norm(b, ord=2)

1.2955324534752801

In [128]:
scipy.spatial.distance.cdist(a[:, np.newaxis], b[:, np.newaxis], metric='euclidean')
# a[:, np.newaxis] добавляет один размер к оси (делает столбцом и 
# мы можем работать с 2мерными матрицами, которые нужны для функции cdist 

array([[ 7.,  6.,  1.],
       [ 4.,  3.,  4.],
       [ 4.,  5., 12.]])

In [129]:
## Задание. Пусть даны два вектора a = np.array([0, -1, 11]) и b = np.array([3, 7, 2]). 
# Какие из следующих команд считают скалярное произведение этих векторов?
a = np.array([0, -1, 11])
b = np.array([3, 7, 2])
# Скалярным произведением является число (когда рассматриваются векторы, числа часто называют скалярами), 
# не зависящее от системы координат и характеризующее длины векторов-сомножителей и угол между ними. 
# Данной операции соответствует умножение длины вектора x на проекцию вектора y на вектор x
# Скалярное произведения <a,b> =  a1*b1 + a2*b2 +  ... an*bn = 15

# np.dot:
# Для двухмерных массивов это эквивалентно матричному умножению, 
# а для 1-D массивов - скалярному произведению векторов (без комплексного сопряжения). 
# Для размерностей N это суммирующий продукт по последней оси а и второй по последнему из b

In [130]:
np.dot(a, b) / np.linalg.norm(a) / np.linalg.norm(b)

0.1724707686818527

In [131]:
np.dot(a, b)

15

In [132]:
b.dot(a)

15

In [133]:
a * b

array([ 0, -7, 22])

In [136]:
## Пусть дан вектор a = np.array([8, 10, -1, 0, 0]). Какие из следующих команд преобразуют вектор a к вектор-столбцу?
a = np.array([8, 10, -1, 0, 0])
a

array([ 8, 10, -1,  0,  0])

In [137]:
b = a.reshape((1, 5))
b

array([[ 8, 10, -1,  0,  0]])

In [138]:
c = a.reshape((5, 1))
c

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [139]:
d = a[np.newaxis, :]
d

array([[ 8, 10, -1,  0,  0]])

In [141]:
e = a[:, np.newaxis]
e

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])