In [1]:
import numpy as np

In [3]:
## Задание 2. Чему равен ранг следующей матрицы?
m = np.array([[1,1,2],[0,1,2]])
print m
print np.linalg.matrix_rank(m)

[[1 1 2]
 [0 1 2]]
2


In [9]:
## Задание 4 К каким классам относится следующая матрица?
m4 = np.array([[1,1],[1,2]])
# Диагоальные - матрицы, у которых числа только по главной диагонали
# Симметричеые - у которых транспонированная матрица равна ей же A=At
# Ортогональная A*At=At*A=I
print m4
print 'Транспонированная матрица. У симметричной равна самой матрице\n', m4.T
print 'Результируащая матрица при умножении на трнаспонированную, для ортогональных должна равняться I\n', m4.dot(m4.T)

[[1 1]
 [1 2]]
Транспонированная матрица. У симметричной равна самой матрице
[[1 1]
 [1 2]]
Результируащая матрица при умножении на трнаспонированную, для ортогональных должна равняться I
[[2 3]
 [3 5]]


In [10]:
## Задание 6 Какие из нижеприведенных команд корректно отработают и создадут двумерный массив?
a = np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])
a

ValueError: only 2 non-keyword arguments accepted

In [11]:
b = np.eye(2, 3)
b

array([[1., 0., 0.],
       [0., 1., 0.]])

In [15]:
c = np.eye((4, 5))

TypeError: 'tuple' object cannot be interpreted as an index

In [16]:
d = np.ones((10, 10))
d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
e = np.arange(1, 13, 2).reshape((3, 2))
e

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [19]:
## Задание 7 Пусть создан массив с помощью команды a = np.eye(4, 5). Что вернет операция a [с опциями:]
# 0
# 3]
# [1
# 3
a = np.eye(4, 5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [21]:
a1 = np.eye(4, 5, 0)
a1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [22]:
a2 = np.eye(4, 5, 3])
a2

SyntaxError: invalid syntax (<ipython-input-22-0d8c992e9f67>, line 1)

In [23]:
a3 = np.eye(4, 5, [1)
a3

SyntaxError: invalid syntax (<ipython-input-23-e6f9ca44ebfb>, line 1)

In [24]:
a4 = np.eye(4, 5, 3)
a4

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
a[0]

array([1., 0., 0., 0., 0.])