In [1]:
import numpy as np

In [12]:
## Задание 2. колько решений у следующей системы линейных уравнений?  2x=3, 2x=4
# Если ранг расширенной матрицы равен рангу матрицы - хотя бы одно решение существует. 
# Если ранг расширенной матрицы больше - решения не существет 
v1 = np.array([2,3])
v2 = np.array([[2, 3], [2,4]])
print v1
print 'Ранг', np.linalg.matrix_rank(v1), 'Размеры', v1.shape, 'Размерность', v1.ndim
print v2 
print  'Ранг', np.linalg.matrix_rank(v2),  'Размеры', v2.shape, 'Размерность', v2.ndim
print 'Провреяем, что есть решение. Ранг расширенной матрицы должен быть равен рангу матрицы (чтобы было решение хотя бы одно):', np.linalg.matrix_rank(v1) == np.linalg.matrix_rank(v2)

[2 3]
Ранг 1 Размеры (2L,) Размерность 1
[[2 3]
 [2 4]]
Ранг 2 Размеры (2L, 2L) Размерность 2
Провреяем, что есть решение. Ранг расширенной матрицы должен быть равен рангу матрицы (чтобы было решение хотя бы одно): False


In [25]:
## Задание 3. Сколько решений у следующей системы линейных уравнений? x + y = 2 , x + 2y = 3
# см. про возмжность решений выше
# Если ранг матрицы равен числу неизвестных (размеру вектора неизвестных) - то решение одно
# Если ранг матрицы меньше числа неизвестных (размера вектора неизвестных - т.е. строки) - то решений бексконечное множество
v3 = np.array([[1,1], [1,2]])
v4 = np.array([[1,1,2], [1,2,3]])

print v3
print 'Ранг матрицы', np.linalg.matrix_rank(v3), 'Размеры', v3.shape, 'Размерность', v3.ndim
print v4 
print  'Ранг расширенной', np.linalg.matrix_rank(v4),  'Размеры', v4.shape, 'Размерность', v4.ndim
print 'Провреяем, что есть решение. Ранг расширенной матрицы должен быть равен рангу матрицы', np.linalg.matrix_rank(v3) == np.linalg.matrix_rank(v4)
if(np.linalg.matrix_rank(v3) == np.linalg.matrix_rank(v4)):
    print 'Решение одно, если ранг матрицы равен размеру вектора незивестных (кол-ву элементов для в строке):', np.linalg.matrix_rank(v3) == len(v3[0])

[[1 1]
 [1 2]]
Ранг матрицы 2 Размеры (2L, 2L) Размерность 2
[[1 1 2]
 [1 2 3]]
Ранг расширенной 2 Размеры (2L, 3L) Размерность 2
Провреяем, что есть решение. Ранг расширенной матрицы должен быть равен рангу матрицы True
Решение одно, если ранг матрицы равен размеру вектора незивестных (кол-ву элементов для в строке): True
